QUEST_TYPE_ARCHON = 1
QUEST_TYPE_STORY = 2
QUEST_TYPE_HANGOUT = 3
QUEST_TYPE_EVENT = 4
QUEST_TYPE_OTHER = 5
QUEST_TYPE_CHARACTER = 6

CHARACTER_AETHER = 0
CHARACTER_LUMINE = 1

BASE_URL = 'https://genshin-impact.fandom.com/'